import {
  DownloadActiveIcon,
  DownloadDefaultIcon,
} from './BaseUI-Icons/Buttons/Download';
import {
  ArrowCircleDefaultMIcon,
  ArrowCircleDefaultSIcon,
  ArrowCircleHoverMIcon,
  ArrowCircleHoverSIcon,
} from './BaseUI-Icons/Buttons/Text+icon-arrow';
import { PlusIcon } from './BaseUI-Icons/Buttons/Text+icon-plus';
import {
  DropdownArrowIcon,
  DropdownCalendarIcon,
  DropdownCheckmarkIcon,
} from './BaseUI-Icons/Dropdown';
import { CheckmarkIcon, UncheckedIcon } from './BaseUI-Icons/PaymentTextField';
import {
  BackArrowCarbonMIcon,
  BackArrowCarbonSIcon,
  BackArrowPurpleMIcon,
  BackArrowPurpleSIcon,
} from './Global-Icons/BackArrows';
import { ChatbotDefaultIcon, ChatbotHoverIcon } from './Global-Icons/Chatbot';
import { CloseXIcon } from './Global-Icons/CloseX';
import {
  HeaderAccountActiveIcon,
  HeaderAccountDefaultIcon,
  HeaderAccountHoverIcon,
  HeaderBellActiveIcon,
  HeaderBellDefaultIcon,
  HeaderBellHoverIcon,
  HeaderNewMsgDefaultIcon,
  HeaderNewMsgHoverIcon,
} from './Global-Icons/DesktopHeaderIcons';
import { DownloadLIcon } from './Global-Icons/Download';
import { HamburgerMenuIcon } from './Global-Icons/HamburgerMenu';
import {
  NavAccountActiveLIcon,
  NavAccountActiveMIcon,
  NavAccountDefaultLIcon,
  NavAccountDefaultMIcon,
  NavCalculatorActiveLIcon,
  NavCalculatorActiveMIcon,
  NavCalculatorDefaultLIcon,
  NavCalculatorDefaultMIcon,
  NavDocumentsActiveLIcon,
  NavDocumentsActiveMIcon,
  NavDocumentsDefaultLIcon,
  NavDocumentsDefaultMIcon,
  NavHelpActiveLIcon,
  NavHelpActiveMIcon,
  NavHelpDefaultLIcon,
  NavHelpDefaultMIcon,
  NavLogoutActiveLIcon,
  NavLogoutActiveMIcon,
  NavLogoutDefaultLIcon,
  NavLogoutDefaultMIcon,
  NavMortgageActiveLIcon,
  NavMortgageActiveMIcon,
  NavMortgageDefaultLIcon,
  NavMortgageDefaultMIcon,
  NavPaymentsActiveLIcon,
  NavPaymentsActiveMIcon,
  NavPaymentsDefaultLIcon,
  NavPaymentsDefaultMIcon,
} from './Global-Icons/Navigation';
import {
  LaptopSplash,
  Login,
  PhoneSplash,
  PiggyBankSplash,
  RegisterClipboard,
  RegisterRobot,
  SelectLoan,
  Welcome,
} from './Illustrations/Login';
import MortgageLogo from './MortgageLogo';

export {
  ArrowCircleDefaultSIcon,
  ArrowCircleHoverSIcon,
  ArrowCircleDefaultMIcon,
  ArrowCircleHoverMIcon,
  BackArrowCarbonSIcon,
  BackArrowPurpleSIcon,
  BackArrowCarbonMIcon,
  BackArrowPurpleMIcon,
  ChatbotDefaultIcon,
  ChatbotHoverIcon,
  CheckmarkIcon,
  CloseXIcon,
  DownloadActiveIcon,
  DownloadDefaultIcon,
  DownloadLIcon,
  DropdownArrowIcon,
  DropdownCalendarIcon,
  DropdownCheckmarkIcon,
  HamburgerMenuIcon,
  HeaderAccountActiveIcon,
  HeaderBellActiveIcon,
  HeaderAccountDefaultIcon,
  HeaderBellDefaultIcon,
  HeaderNewMsgDefaultIcon,
  HeaderAccountHoverIcon,
  HeaderBellHoverIcon,
  HeaderNewMsgHoverIcon,
  LaptopSplash,
  Login,
  MortgageLogo,
  NavAccountActiveMIcon,
  NavCalculatorActiveMIcon,
  NavDocumentsActiveMIcon,
  NavHelpActiveMIcon,
  NavLogoutActiveMIcon,
  NavMortgageActiveMIcon,
  NavPaymentsActiveMIcon,
  NavAccountDefaultMIcon,
  NavCalculatorDefaultMIcon,
  NavDocumentsDefaultMIcon,
  NavHelpDefaultMIcon,
  NavLogoutDefaultMIcon,
  NavMortgageDefaultMIcon,
  NavPaymentsDefaultMIcon,
  NavAccountActiveLIcon,
  NavCalculatorActiveLIcon,
  NavDocumentsActiveLIcon,
  NavHelpActiveLIcon,
  NavLogoutActiveLIcon,
  NavMortgageActiveLIcon,
  NavPaymentsActiveLIcon,
  NavAccountDefaultLIcon,
  NavCalculatorDefaultLIcon,
  NavDocumentsDefaultLIcon,
  NavHelpDefaultLIcon,
  NavLogoutDefaultLIcon,
  NavMortgageDefaultLIcon,
  NavPaymentsDefaultLIcon,
  PhoneSplash,
  PiggyBankSplash,
  PlusIcon,
  RegisterClipboard,
  RegisterRobot,
  SelectLoan,
  UncheckedIcon,
  Welcome,
};
